# Generated by Django 2.2.12 on 2020-08-07 03:04

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threshold_public_goods_end_group', to='otree.Session')),
            ],
            options={
                'db_table': 'threshold_public_goods_end_group',
            },
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threshold_public_goods_end_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'threshold_public_goods_end_subsession',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_is_waiting', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('birth_year', otree.db.models.IntegerField(null=True, verbose_name='What is your year of birth?')),
                ('gender', otree.db.models.IntegerField(choices=[[0, 'Male'], [1, 'Female'], [2, 'Other']], null=True, verbose_name='What is your gender identity?')),
                ('education', otree.db.models.IntegerField(choices=[[0, 'Did not complete High School'], [1, 'Graduated from High School'], [2, 'Some College Degree'], [3, 'Bachelor’s Degree'], [4, 'Master’s Degree'], [5, 'Ph.D. or higher']], null=True, verbose_name='What is the highest education qualification you have attained?')),
                ('income', otree.db.models.IntegerField(choices=[[0, 'less than $20,000'], [1, '$20,000-$39,999'], [2, '$40,000-$59,999'], [3, '$60,000-$79,999'], [4, '$80,000-$99,999'], [5, '$100,000 or more']], null=True, verbose_name='Please select your household annual income from the options below:')),
                ('ethnicity', otree.db.models.IntegerField(choices=[[0, 'White'], [1, 'Black or African American'], [2, 'American Indian or Alaskan Native'], [3, 'Asian'], [4, 'Native Hawaiian or Pacific Islander'], [5, 'Hispanic or Latino'], [6, 'Middle Eastern or Arab'], [7, 'Other (please state below)']], null=True, verbose_name='What is your ethnicity?')),
                ('other', otree.db.models.StringField(blank=True, max_length=10000, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='threshold_public_goods_end.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threshold_public_goods_end_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threshold_public_goods_end_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threshold_public_goods_end.Subsession')),
            ],
            options={
                'db_table': 'threshold_public_goods_end_player',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threshold_public_goods_end.Subsession'),
        ),
    ]
