# Generated by Django 2.2.12 on 2020-07-27 17:54

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('threshold_public_goods', '0003_player_attention_check_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='attention_check_1',
            field=otree.db.models.IntegerField(choices=[[0, 'dog'], [0, 'cat'], [1, 'rabbit']], default=[0, 'no selection'], null=True),
        ),
    ]
