# Generated by Django 2.2.12 on 2020-08-03 22:02

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('threshold_public_goods', '0013_player_attention_check_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='GroupACon',
            field=otree.db.models.CurrencyField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='GroupBCon',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
