# Generated by Django 2.2.12 on 2020-08-03 22:18

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('threshold_public_goods', '0014_auto_20200803_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='GroupACon',
        ),
        migrations.AddField(
            model_name='player',
            name='contribution_acc_a',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
