# Generated by Django 2.2.12 on 2020-08-03 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threshold_public_goods', '0015_auto_20200803_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='GroupBCon',
        ),
        migrations.RemoveField(
            model_name='player',
            name='contribution_acc_a',
        ),
    ]
