# Generated by Django 2.2.12 on 2020-08-25 19:07

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('threshold_public_goods', '0016_auto_20200803_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='attention_check_1',
            field=otree.db.models.IntegerField(choices=[[0, 'no selection'], [0, 'dog'], [0, 'cat'], [1, 'rabbit']], default=0, null=True, verbose_name='This question is to check your attention. Please select rabbit'),
        ),
        migrations.AlterField(
            model_name='player',
            name='attention_check_2',
            field=otree.db.models.IntegerField(choices=[[0, 'no selection'], [0, 'bye'], [1, 'hello'], [0, 'good']], default=0, null=True, verbose_name='This question is to check your attention. Please select hello'),
        ),
    ]
